name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  main:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.8.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm --filter './packages/*' run build

      - name: Run all checks
        run: pnpm lint && pnpm test && pnpm build && pnpm typecheck
